---

version: '3'

includes:
  ext_vars: './variables.yaml'
  secrets: './.secrets.yaml'

vars:
  ARCH:
    sh: "echo $(uname -m)"
  LOCAL_PLATFORM: "linux/{{ .ARCH }}"

tasks:
  build_load:
    label: 'Build image and load to Docker'
    cmd: "IMAGE_NAMESPACE={{ .IMAGE_NAMESPACE }} VERSION={{ .VERSION }} LOCAL_PLATFORM={{ .LOCAL_PLATFORM }} docker buildx bake load"

  build_push:
    label: 'Build image and push to DockerHub'
    cmds:
      - "docker login -u {{ .DOCKERHUB_LOGIN }} -p {{ .DOCKERHUB_PASSWORD }}"
      - "IMAGE_NAMESPACE={{ .IMAGE_NAMESPACE }} VERSION={{ .VERSION }} docker buildx bake push"

  run:
    label: 'Run container'
    cmd: "docker run {{ .IMAGE_NAMESPACE }}:{{ .VERSION }}"

  run_background:
    label: 'Run container in background'
    cmd: "docker run -d {{ .IMAGE_NAMESPACE }}:{{ .VERSION }}"
