---

version: '3'

includes:
  ext_vars: './variables.yaml'
  secrets: './.secrets.yaml'

vars:
  ARCH:
    sh: "echo $(uname -m)"
  LOCAL_PLATFORM: "linux/{{ .ARCH }}"

tasks:
  build_load:
    label: 'Build image and load to Docker'
    cmd: "docker buildx bake load"
    env:
      IMAGE_NAMESPACE: "{{ .IMAGE_NAMESPACE }}"
      VERSION: "{{ .VERSION }}"
      LOCAL_PLATFORM: "{{ .LOCAL_PLATFORM }}"
      GO_JSONNET_VERSION: "{{ .GO_JSONNET_VERSION }}"
      GO_JSONNET_LINTER_VERSION: "{{ .GO_JSONNET_LINTER_VERSION }}"
      JSONNET_BUNDLER_VERSION: "{{ .JSONNET_BUNDLER_VERSION }}"

  build_push:
    label: 'Build image and push to DockerHub'
    cmds:
      - "docker login -u {{ .DOCKERHUB_LOGIN }} -p {{ .DOCKERHUB_PASSWORD }}"
      - "IMAGE_NAMESPACE={{ .IMAGE_NAMESPACE }} VERSION={{ .VERSION }} docker buildx bake push"

  run:
    label: 'Run container'
    cmd: "docker run -it --rm {{ .IMAGE_NAMESPACE }}:{{ .VERSION }}"

  run_install_grafonnet:
    label: 'Run container and install grafonnet'
    cmd: "docker run -it --rm {{ .IMAGE_NAMESPACE }}:{{ .VERSION }} jb install github.com/grafana/grafonnet/gen/grafonnet-latest@main"

  run_background:
    label: 'Run container in background'
    cmd: "docker run -d {{ .IMAGE_NAMESPACE }}:{{ .VERSION }}"
